name: build

on: [push, pull_request]

jobs:
  run-test:
    runs-on: self-hosted
    strategy:
      matrix:
        destination: [
          'macOS', 
          'iOS Simulator,name=iPhone 15', 
          'tvOS Simulator,name=Apple TV', 
          'watchOS Simulator,name=Apple Watch Series 8 (41mm)'
        ]
        xcode: [
          '15.2',
          '15.3'
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          self-hosted: true
      - name: Run tests
        env:
          DESTINATION: platform=${{ matrix.destination }}
          XCODE_VERSION: ${{ matrix.xcode }}
        run: bundle exec fastlane test_ci
